In [ ]:
from google.colab import  drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import os 
os.environ["KAGGLE_CONFIG_DIR"]="/content/gdrive/MyDrive/fake news/kaggle.json"

In [ ]:
%cd "/content/gdrive/MyDrive/fake news"

/content/gdrive/MyDrive/fake news


In [ ]:
import numpy as np
import nltk
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
import re



In [ ]:
df=pd.read_csv("train.csv")
print(df.shape)
df.head()

(20800, 5)


id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [ ]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [ ]:
df=df.dropna()
df.reset_index(inplace=True)
df["content"]=df['author']+" "+df['title']

In [ ]:

nltk.download('stopwords')
stem=PorterStemmer()
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]', ' ',content) # this basically replaces everything other than lower a-z & upper A-Z with a ' ', for eg apple,bananna --> apple bananna
    stemmed_content = stemmed_content.lower() # to make all text lower case
    stemmed_content = stemmed_content.split() # this basically splits the line into words with delimiter as ' '
    stemmed_content = [stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')] # basically remove all the stopwords and apply stemming to the final data
    stemmed_content = ' '.join(stemmed_content) # this basically joins back and returns the cleaned sentence
    return stemmed_content

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
df['content'] = df['content'].apply(stemming)
df.head()

index  id  ... label                                            content
0      0   0  ...     1  darrel lucu hous dem aid even see comey letter...
1      1   1  ...     0  daniel j flynn flynn hillari clinton big woman...
2      2   2  ...     1             consortiumnew com truth might get fire
3      3   3  ...     1  jessica purkiss civilian kill singl us airstri...
4      4   4  ...     1  howard portnoy iranian woman jail fiction unpu...

[5 rows x 7 columns]

In [ ]:
X = df['content'].values
y = df['label'].values

In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(X)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state = 0)
from sklearn.metrics import confusion_matrix,accuracy_score
classifier = LogisticRegression(C = 100, penalty = 'l2', solver= 'newton-cg')
classifier.fit(x_train, y_train)

LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
ypred=classifier.predict(x_test)
accuracy_score(y_test,y_pred=ypred)


0.9937106918238994

In [ ]:
logit=LogisticRegression()
knn=KNeighborsClassifier()
rf=RandomForestClassifier()
dt=DecisionTreeClassifier()
mnb=MultinomialNB()
xg=XGBClassifier()
algorithms=[logit,knn,rf,dt,mnb,xg]

for algorithm in algorithms:
  algorithm.fit(x_train,y_train)
  y_pred=algorithm.predict(x_test)
  print("algorithm used"+" "+str(algorithm))
  print(confusion_matrix(y_test,y_pred=y_pred))
  print(accuracy_score(y_test,y_pred=y_pred))

algorithm used LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
[[2016   24]
 [  12 1605]]
0.9901558654634947
algorithm used KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')
[[1112  928]
 [   3 1614]]
0.7454197429587093
algorithm used RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2

In [ ]:
X = df['content']
y = df['label']

In [ ]:
tfidf=TfidfVectorizer()
x=tfidf.fit_transform(X)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state = 0)
ogit=LogisticRegression()
knn=KNeighborsClassifier()
rf=RandomForestClassifier()
dt=DecisionTreeClassifier()
mnb=MultinomialNB()
xg=XGBClassifier()
algorithms=[logit,knn,rf,dt,mnb,xg]

for algorithm in algorithms:
  algorithm.fit(x_train,y_train)
  y_pred=algorithm.predict(x_test)
  print("algorithm used"+" "+str(algorithm))
  print(confusion_matrix(y_test,y_pred=y_pred))
  print(accuracy_score(y_test,y_pred=y_pred))

algorithm used LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
[[1985   55]
 [  16 1601]]
0.9805851791085589
algorithm used KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')
[[  92 1948]
 [   0 1617]]
0.4673229423024337
algorithm used RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2

## logitic regression is working so well so that we dont need any more hyper parameter optimization
## Bag of Words giving better accuracy than the TF-IDF